In [1]:
x=5

In [2]:
import os
os.chdir(r'C:\Users\Admin\Downloads')

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('Recommend.csv', names = ['user_id','movie_id','rating','timestamp'])
df

       user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0]

In [6]:
n_users

943

In [7]:
n_movies = df.movie_id.unique().shape[0]

In [8]:
n_movies

1682

In [9]:
train_data, test_data = train_test_split(df, test_size = 0.25)

In [10]:
train_data_matrix = np.zeros((n_users, n_movies))

In [16]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]
pd.DataFrame(train_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,5.0,0.0,0.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,2.0,0.0,0.0,0.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
pd.DataFrame(test_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
test_data_matrix[588,878]

4.0

In [20]:
tuple(test_data.itertuples())

(Pandas(Index=66445, user_id=589, movie_id=879, rating=4, timestamp=883352654),
 Pandas(Index=21326, user_id=13, movie_id=559, rating=1, timestamp=882396913),
 Pandas(Index=32621, user_id=425, movie_id=127, rating=4, timestamp=878738290),
 Pandas(Index=19285, user_id=274, movie_id=471, rating=4, timestamp=878945505),
 Pandas(Index=34168, user_id=393, movie_id=739, rating=3, timestamp=887746671),
 Pandas(Index=58430, user_id=622, movie_id=396, rating=1, timestamp=882671222),
 Pandas(Index=88550, user_id=709, movie_id=288, rating=5, timestamp=879847945),
 Pandas(Index=50197, user_id=763, movie_id=88, rating=4, timestamp=878918486),
 Pandas(Index=40508, user_id=312, movie_id=490, rating=5, timestamp=891699655),
 Pandas(Index=39054, user_id=551, movie_id=240, rating=3, timestamp=892784673),
 Pandas(Index=5905, user_id=318, movie_id=524, rating=3, timestamp=884496123),
 Pandas(Index=90208, user_id=886, movie_id=117, rating=2, timestamp=876033624),
 Pandas(Index=52881, user_id=758, movie_id=163, rating=5, timestamp=881976089),
 Pandas(Index=41574, user_id=450, movie_id=491, rating=3, timestamp=882373297),
 Pandas(Index=72001, user_id=575, movie_id=176, rating=4, timestamp=878148087),
 Pandas(Index=56304, user_id=807, movie_id=405, rating=4, timestamp=892684722),
 Pandas(Index=26842, user_id=19, movie_id=887, rating=4, timestamp=885411465),
 Pandas(Index=70587, user_id=452, movie_id=607, rating=5, timestamp=875266680),
 Pandas(Index=15072, user_id=184, movie_id=568, rating=2, timestamp=889909474),
 Pandas(Index=29624, user_id=141, movie_id=261, rating=1, timestamp=886447904),
 Pandas(Index=9415, user_id=264, movie_id=4, rating=4, timestamp=886123656),
 Pandas(Index=89863, user_id=460, movie_id=13, rating=3, timestamp=882912371),
 Pandas(Index=19740, user_id=401, movie_id=501, rating=2, timestamp=891033184),
 Pandas(Index=57423, user_id=1, movie_id=195, rating=5, timestamp=876892855),
 Pandas(Index=45474, user_id=269, movie_id=196, rating=1, timestamp=891448283),
 Pandas(Index=958, user_id=197, movie_id=347, rating=4, timestamp=891409070),
 Pandas(Index=76838, user_id=915, movie_id=307, rating=3, timestamp=891030032),
 Pandas(Index=33600, user_id=97, movie_id=191, rating=5, timestamp=884239472),
 Pandas(Index=78172, user_id=797, movie_id=1254, rating=2, timestamp=879439548),
 Pandas(Index=47161, user_id=339, movie_id=1404, rating=5, timestamp=891034592),
 Pandas(Index=26505, user_id=525, movie_id=123, rating=3, timestamp=881086051),
 Pandas(Index=90147, user_id=936, movie_id=221, rating=4, timestamp=886832373),
 Pandas(Index=14636, user_id=406, movie_id=501, rating=5, timestamp=879793081),
 Pandas(Index=32000, user_id=486, movie_id=1017, rating=3, timestamp=879874970),
 Pandas(Index=79923, user_id=42, movie_id=73, rating=4, timestamp=881108484),
 Pandas(Index=79150, user_id=654, movie_id=462, rating=4, timestamp=887864998),
 Pandas(Index=2492, user_id=313, movie_id=673, rating=4, timestamp=891016622),
 Pandas(Index=69331, user_id=110, movie_id=939, rating=4, timestamp=886988042),
 Pandas(Index=25670, user_id=23, movie_id=530, rating=4, timestamp=874789279),
 Pandas(Index=33698, user_id=543, movie_id=385, rating=3, timestamp=877545717),
 Pandas(Index=66762, user_id=843, movie_id=176, rating=4, timestamp=879447837),
 Pandas(Index=30235, user_id=75, movie_id=1, rating=4, timestamp=884050018),
 Pandas(Index=44017, user_id=653, movie_id=196, rating=2, timestamp=880151539),
 Pandas(Index=89471, user_id=875, movie_id=269, rating=4, timestamp=876464694),
 Pandas(Index=87465, user_id=437, movie_id=401, rating=5, timestamp=880143505),
 Pandas(Index=56692, user_id=843, movie_id=452, rating=2, timestamp=879443442),
 Pandas(Index=34205, user_id=532, movie_id=403, rating=4, timestamp=892865321),
 Pandas(Index=25083, user_id=417, movie_id=1139, rating=3, timestamp=879649448),
 Pandas(Index=79779, user_id=933, movie_id=765, rating=1, timestamp=874938644),
 Pandas(Index=23267, user_id=325, movie_id=1, rating=2, timestamp=891478665),
 Pandas(Index=74815, user_id=897, movie_id=410, rating=3, timestamp=879993621),
 Pandas(Index=27587, user_id=246, movie_id=24, rating=4, timestamp=884921345),
 Pandas(Index=24364, user_id=194, movie_id=498, rating=3, timestamp=879521595),
 Pandas(Index=22427, user_id=336, movie_id=122, rating=5, timestamp=877757134),
 Pandas(Index=72282, user_id=826, movie_id=679, rating=2, timestamp=885690712),
 Pandas(Index=64623, user_id=705, movie_id=215, rating=2, timestamp=883518871),
 Pandas(Index=65249, user_id=637, movie_id=596, rating=2, timestamp=882903582),
 Pandas(Index=95912, user_id=524, movie_id=175, rating=3, timestamp=884634911),
 Pandas(Index=33107, user_id=189, movie_id=487, rating=5, timestamp=893265568),
 Pandas(Index=51555, user_id=290, movie_id=49, rating=3, timestamp=880475542),
 Pandas(Index=29918, user_id=442, movie_id=800, rating=3, timestamp=883390139),
 Pandas(Index=98819, user_id=870, movie_id=1412, rating=2, timestamp=879714435),
 Pandas(Index=10472, user_id=50, movie_id=9, rating=4, timestamp=877052297),
 Pandas(Index=16610, user_id=318, movie_id=657, rating=5, timestamp=884495696),
 Pandas(Index=30523, user_id=483, movie_id=405, rating=3, timestamp=878952966),
 Pandas(Index=98129, user_id=938, movie_id=106, rating=5, timestamp=891357019),
 Pandas(Index=90895, user_id=200, movie_id=465, rating=4, timestamp=884129112),
 Pandas(Index=9092, user_id=176, movie_id=100, rating=5, timestamp=886047918),
 Pandas(Index=56316, user_id=49, movie_id=93, rating=5, timestamp=888068912),
 Pandas(Index=72754, user_id=943, movie_id=549, rating=1, timestamp=888639772),
 Pandas(Index=44642, user_id=313, movie_id=300, rating=4, timestamp=891012907),
 Pandas(Index=37520, user_id=600, movie_id=1231, rating=2, timestamp=888452152),
 Pandas(Index=25577, user_id=178, movie_id=38, rating=3, timestamp=882827574),
 Pandas(Index=9735, user_id=310, movie_id=14, rating=5, timestamp=879436268),
 Pandas(Index=91496, user_id=342, movie_id=324, rating=1, timestamp=874984002),
 Pandas(Index=52462, user_id=417, movie_id=294, rating=4, timestamp=879646463),
 Pandas(Index=71678, user_id=900, movie_id=471, rating=2, timestamp=877833259),
 Pandas(Index=47499, user_id=158, movie_id=325, rating=4, timestamp=880133920),
 Pandas(Index=16308, user_id=8, movie_id=127, rating=5, timestamp=879362123),
 Pandas(Index=84489, user_id=912, movie_id=186, rating=3, timestamp=875966202),
 Pandas(Index=42941, user_id=472, movie_id=577, rating=3, timestamp=875982680),
 Pandas(Index=15903, user_id=254, movie_id=419, rating=4, timestamp=886472231),
 Pandas(Index=27297, user_id=314, movie_id=1267, rating=3, timestamp=877888117),
 Pandas(Index=24374, user_id=450, movie_id=7, rating=4, timestamp=882376885),
 Pandas(Index=45127, user_id=189, movie_id=151, rating=5, timestamp=893264378),
 Pandas(Index=16409, user_id=343, movie_id=382, rating=3, timestamp=876406978),
 Pandas(Index=99574, user_id=902, movie_id=879, rating=4, timestamp=879463485),
 Pandas(Index=23123, user_id=398, movie_id=485, rating=5, timestamp=875657857),
 Pandas(Index=97885, user_id=13, movie_id=893, rating=3, timestamp=882774005),
 Pandas(Index=65890, user_id=176, movie_id=293, rating=5, timestamp=886048040),
 Pandas(Index=12045, user_id=262, movie_id=318, rating=5, timestamp=879793022),
 Pandas(Index=50181, user_id=621, movie_id=584, rating=5, timestamp=874965094),
 Pandas(Index=68664, user_id=586, movie_id=569, rating=3, timestamp=884060807),
 Pandas(Index=49796, user_id=94, movie_id=215, rating=4, timestamp=891722174),
 Pandas(Index=91898, user_id=320, movie_id=597, rating=3, timestamp=884748774),
 Pandas(Index=90863, user_id=885, movie_id=393, rating=3, timestamp=885713680),
 Pandas(Index=59436, user_id=308, movie_id=131, rating=4, timestamp=887739383),
 Pandas(Index=57559, user_id=194, movie_id=72, rating=3, timestamp=879554100),
 Pandas(Index=43004, user_id=174, movie_id=623, rating=3, timestamp=886515532),
 Pandas(Index=47588, user_id=200, movie_id=202, rating=5, timestamp=884129275),
 Pandas(Index=32792, user_id=585, movie_id=1347, rating=2, timestamp=891285658),
 Pandas(Index=39345, user_id=311, movie_id=700, rating=3, timestamp=884365852),
 Pandas(Index=88110, user_id=854, movie_id=469, rating=5, timestamp=882814571),
 Pandas(Index=16528, user_id=398, movie_id=191, rating=4, timestamp=875721348),
 Pandas(Index=94323, user_id=26, movie_id=248, rating=3, timestamp=891377468),
 Pandas(Index=35188, user_id=120, movie_id=1, rating=4, timestamp=889490412),
 Pandas(Index=77967, user_id=655, movie_id=1174, rating=3, timestamp=887523477),
 Pandas(Index=83846, user_id=868, movie_id=946, rating=1, timestamp=877107189),
 Pandas(Index=47542, user_id=130, movie_id=1088, rating=2, timestamp=876250805),
 Pandas(Index=68462, user_id=766, movie_id=602, rating=4, timestamp=891310038),
 Pandas(Index=97507, user_id=876, movie_id=523, rating=5, timestamp=879428378),
 Pandas(Index=82233, user_id=919, movie_id=558, rating=5, timestamp=875372988),
 Pandas(Index=32338, user_id=493, movie_id=265, rating=5, timestamp=884131048),
 Pandas(Index=56174, user_id=379, movie_id=194, rating=5, timestamp=880525194),
 Pandas(Index=6091, user_id=308, movie_id=736, rating=3, timestamp=887738760),
 Pandas(Index=49670, user_id=95, movie_id=196, rating=4, timestamp=879198354),
 Pandas(Index=15827, user_id=363, movie_id=387, rating=1, timestamp=891497639),
 Pandas(Index=59068, user_id=478, movie_id=447, rating=4, timestamp=889396732),
 Pandas(Index=2465, user_id=110, movie_id=1179, rating=2, timestamp=886989501),
 Pandas(Index=10460, user_id=13, movie_id=601, rating=4, timestamp=882140104),
 Pandas(Index=80152, user_id=515, movie_id=538, rating=3, timestamp=887658676),
 Pandas(Index=3137, user_id=198, movie_id=640, rating=3, timestamp=884208651),
 Pandas(Index=118, user_id=279, movie_id=832, rating=3, timestamp=881375854),
 Pandas(Index=29378, user_id=399, movie_id=760, rating=1, timestamp=882341554),
 Pandas(Index=854, user_id=311, movie_id=654, rating=3, timestamp=884365075),
 Pandas(Index=76421, user_id=861, movie_id=301, rating=4, timestamp=881274504),
 Pandas(Index=55641, user_id=35, movie_id=326, rating=3, timestamp=875459017),
 Pandas(Index=88048, user_id=758, movie_id=276, rating=2, timestamp=881976574),
 Pandas(Index=86658, user_id=326, movie_id=514, rating=3, timestamp=879875612),
 Pandas(Index=52307, user_id=224, movie_id=70, rating=2, timestamp=888103812),
 Pandas(Index=31868, user_id=479, movie_id=101, rating=4, timestamp=879462185),
 Pandas(Index=41964, user_id=162, movie_id=403, rating=3, timestamp=877636713),
 Pandas(Index=65652, user_id=894, movie_id=281, rating=3, timestamp=880416102),
 Pandas(Index=96121, user_id=911, movie_id=478, rating=5, timestamp=892838823),
 Pandas(Index=26791, user_id=452, movie_id=1427, rating=5, timestamp=885816768),
 Pandas(Index=35828, user_id=417, movie_id=15, rating=5, timestamp=879646166),
 Pandas(Index=42785, user_id=395, movie_id=196, rating=4, timestamp=883764378),
 Pandas(Index=9617, user_id=198, movie_id=184, rating=3, timestamp=884209003),
 Pandas(Index=29112, user_id=339, movie_id=195, rating=3, timestamp=891032576),
 Pandas(Index=42873, user_id=458, movie_id=589, rating=4, timestamp=886396140),
 Pandas(Index=37229, user_id=492, movie_id=923, rating=5, timestamp=879969878),
 Pandas(Index=94832, user_id=756, movie_id=622, rating=3, timestamp=874830790),
 Pandas(Index=16162, user_id=398, movie_id=216, rating=5, timestamp=875723337),
 Pandas(Index=51335, user_id=527, movie_id=200, rating=3, timestamp=879455999),
 Pandas(Index=31223, user_id=110, movie_id=765, rating=3, timestamp=886989028),
 Pandas(Index=67981, user_id=465, movie_id=48, rating=3, timestamp=883530313),
 Pandas(Index=83681, user_id=934, movie_id=65, rating=4, timestamp=891192914),
 Pandas(Index=71628, user_id=852, movie_id=260, rating=3, timestamp=891036414),
 Pandas(Index=7304, user_id=233, movie_id=212, rating=5, timestamp=877665324),
 Pandas(Index=75892, user_id=645, movie_id=656, rating=4, timestamp=892053241),
 Pandas(Index=11138, user_id=186, movie_id=288, rating=1, timestamp=879022858),
 Pandas(Index=23850, user_id=419, movie_id=223, rating=4, timestamp=879435785),
 Pandas(Index=59343, user_id=840, movie_id=498, rating=5, timestamp=891204264),
 Pandas(Index=24429, user_id=405, movie_id=1267, rating=1, timestamp=885546379),
 Pandas(Index=70601, user_id=537, movie_id=185, rating=4, timestamp=886030805),
 Pandas(Index=42253, user_id=655, movie_id=576, rating=2, timestamp=888893313),
 Pandas(Index=42464, user_id=291, movie_id=456, rating=3, timestamp=874834165),
 Pandas(Index=42995, user_id=445, movie_id=333, rating=2, timestamp=890987410),
 Pandas(Index=38654, user_id=363, movie_id=172, rating=5, timestamp=891495711),
 Pandas(Index=69035, user_id=716, movie_id=497, rating=3, timestamp=879795949),
 Pandas(Index=78993, user_id=500, movie_id=1135, rating=3, timestamp=883875561),
 Pandas(Index=59075, user_id=458, movie_id=298, rating=5, timestamp=886396677),
 Pandas(Index=83219, user_id=908, movie_id=525, rating=4, timestamp=879722300),
 Pandas(Index=6798, user_id=295, movie_id=1459, rating=5, timestamp=879519237),
 Pandas(Index=74831, user_id=436, movie_id=167, rating=3, timestamp=887770403),
 Pandas(Index=44248, user_id=235, movie_id=1176, rating=5, timestamp=889655820),
 Pandas(Index=70079, user_id=741, movie_id=742, rating=4, timestamp=891455766),
 Pandas(Index=59044, user_id=198, movie_id=823, rating=2, timestamp=884206587),
 Pandas(Index=42645, user_id=63, movie_id=480, rating=3, timestamp=875748245),
 Pandas(Index=24951, user_id=354, movie_id=660, rating=3, timestamp=891218155),
 Pandas(Index=15433, user_id=206, movie_id=895, rating=5, timestamp=888179788),
 Pandas(Index=81796, user_id=667, movie_id=283, rating=4, timestamp=891034947),
 Pandas(Index=53062, user_id=514, movie_id=194, rating=4, timestamp=875463525),
 Pandas(Index=92943, user_id=286, movie_id=215, rating=3, timestamp=889651630),
 Pandas(Index=7793, user_id=342, movie_id=1368, rating=5, timestamp=874984507),
 Pandas(Index=7039, user_id=119, movie_id=87, rating=5, timestamp=874781829),
 Pandas(Index=94667, user_id=606, movie_id=546, rating=4, timestamp=878149278),
 Pandas(Index=28199, user_id=18, movie_id=132, rating=5, timestamp=880132437),
 Pandas(Index=11614, user_id=255, movie_id=259, rating=3, timestamp=883215759),
 Pandas(Index=32294, user_id=506, movie_id=490, rating=3, timestamp=874873529),
 Pandas(Index=15620, user_id=32, movie_id=245, rating=2, timestamp=883710047),
 Pandas(Index=9481, user_id=110, movie_id=232, rating=3, timestamp=886988449),
 Pandas(Index=81262, user_id=886, movie_id=726, rating=1, timestamp=876033340),
 Pandas(Index=74152, user_id=790, movie_id=763, rating=3, timestamp=884462692),
 Pandas(Index=96476, user_id=794, movie_id=257, rating=4, timestamp=891036265),
 Pandas(Index=56159, user_id=565, movie_id=512, rating=3, timestamp=891037453),
 Pandas(Index=32199, user_id=379, movie_id=205, rating=5, timestamp=880524973),
 Pandas(Index=98605, user_id=761, movie_id=628, rating=4, timestamp=876190689),
 Pandas(Index=4536, user_id=210, movie_id=219, rating=3, timestamp=887808581),
 Pandas(Index=43099, user_id=294, movie_id=111, rating=4, timestamp=877819999),
 Pandas(Index=96256, user_id=603, movie_id=7, rating=5, timestamp=891956075),
 Pandas(Index=53259, user_id=705, movie_id=191, rating=1, timestamp=883518871),
 Pandas(Index=84629, user_id=804, movie_id=152, rating=4, timestamp=879445466),
 Pandas(Index=30016, user_id=244, movie_id=246, rating=5, timestamp=880604302),
 Pandas(Index=61072, user_id=327, movie_id=718, rating=4, timestamp=887745494),
 Pandas(Index=39011, user_id=527, movie_id=517, rating=5, timestamp=879456186),
 Pandas(Index=82400, user_id=321, movie_id=221, rating=5, timestamp=879438793),
 Pandas(Index=41125, user_id=11, movie_id=430, rating=3, timestamp=891905032),
 Pandas(Index=95212, user_id=128, movie_id=180, rating=5, timestamp=879967174),
 Pandas(Index=68015, user_id=896, movie_id=872, rating=3, timestamp=887157322),
 Pandas(Index=26285, user_id=46, movie_id=245, rating=3, timestamp=883614625),
 Pandas(Index=15794, user_id=331, movie_id=242, rating=4, timestamp=877196089),
 Pandas(Index=36525, user_id=621, movie_id=541, rating=4, timestamp=874964605),
 Pandas(Index=61395, user_id=846, movie_id=516, rating=4, timestamp=883948457),
 Pandas(Index=46844, user_id=300, movie_id=833, rating=4, timestamp=875650329),
 Pandas(Index=87193, user_id=901, movie_id=391, rating=5, timestamp=877131205),
 Pandas(Index=11599, user_id=83, movie_id=452, rating=3, timestamp=880309214),
 Pandas(Index=281, user_id=181, movie_id=872, rating=1, timestamp=878961814),
 Pandas(Index=47682, user_id=715, movie_id=73, rating=4, timestamp=875964410),
 Pandas(Index=48192, user_id=207, movie_id=82, rating=3, timestamp=877125249),
 Pandas(Index=40195, user_id=537, movie_id=458, rating=3, timestamp=886030176),
 Pandas(Index=3093, user_id=160, movie_id=3, rating=3, timestamp=876770124),
 Pandas(Index=51080, user_id=665, movie_id=31, rating=3, timestamp=884294880),
 Pandas(Index=33930, user_id=342, movie_id=535, rating=3, timestamp=874984727),
 Pandas(Index=93489, user_id=535, movie_id=419, rating=3, timestamp=879618654),
 Pandas(Index=95040, user_id=755, movie_id=301, rating=3, timestamp=882569771),
 Pandas(Index=97389, user_id=868, movie_id=2, rating=2, timestamp=877112290),
 Pandas(Index=80373, user_id=815, movie_id=217, rating=3, timestamp=878696681),
 Pandas(Index=22122, user_id=123, movie_id=504, rating=5, timestamp=879872948),
 Pandas(Index=51735, user_id=701, movie_id=750, rating=5, timestamp=891446588),
 Pandas(Index=74975, user_id=313, movie_id=89, rating=5, timestamp=891014373),
 Pandas(Index=58143, user_id=768, movie_id=111, rating=3, timestamp=880136139),
 Pandas(Index=78587, user_id=48, movie_id=243, rating=3, timestamp=879434330),
 Pandas(Index=42380, user_id=620, movie_id=895, rating=3, timestamp=889986984),
 Pandas(Index=940, user_id=196, movie_id=393, rating=4, timestamp=881251863),
 Pandas(Index=6171, user_id=296, movie_id=950, rating=4, timestamp=884196741),
 Pandas(Index=37415, user_id=533, movie_id=181, rating=5, timestamp=879191085),
 Pandas(Index=75483, user_id=758, movie_id=151, rating=5, timestamp=881975814),
 Pandas(Index=82369, user_id=524, movie_id=386, rating=4, timestamp=884637032),
 Pandas(Index=79283, user_id=577, movie_id=1219, rating=3, timestamp=880475067),
 Pandas(Index=84092, user_id=786, movie_id=179, rating=4, timestamp=882843500),
 Pandas(Index=93672, user_id=711, movie_id=472, rating=1, timestamp=879991585),
 Pandas(Index=38922, user_id=454, movie_id=497, rating=3, timestamp=881959876),
 Pandas(Index=99352, user_id=932, movie_id=431, rating=3, timestamp=891250944),
 Pandas(Index=37983, user_id=430, movie_id=294, rating=2, timestamp=877225239),
 Pandas(Index=9517, user_id=77, movie_id=210, rating=3, timestamp=884753028),
 Pandas(Index=54570, user_id=342, movie_id=262, rating=2, timestamp=874984025),
 Pandas(Index=46377, user_id=514, movie_id=486, rating=3, timestamp=886189869),
 Pandas(Index=36486, user_id=308, movie_id=679, rating=4, timestamp=887739426),
 Pandas(Index=21121, user_id=305, movie_id=96, rating=3, timestamp=886324172),
 Pandas(Index=43929, user_id=230, movie_id=121, rating=4, timestamp=880484998),
 Pandas(Index=82843, user_id=927, movie_id=72, rating=5, timestamp=879193848),
 Pandas(Index=10126, user_id=129, movie_id=269, rating=4, timestamp=883244011),
 Pandas(Index=83402, user_id=815, movie_id=1157, rating=2, timestamp=884267828),
 Pandas(Index=74928, user_id=724, movie_id=1127, rating=3, timestamp=883758267),
 Pandas(Index=85111, user_id=846, movie_id=527, rating=5, timestamp=883947500),
 Pandas(Index=37266, user_id=478, movie_id=137, rating=4, timestamp=889398260),
 Pandas(Index=96750, user_id=21, movie_id=273, rating=4, timestamp=874951349),
 Pandas(Index=41615, user_id=368, movie_id=98, rating=3, timestamp=889783407),
 Pandas(Index=88363, user_id=847, movie_id=196, rating=3, timestamp=878939839),

In [30]:
pd.DataFrame(test_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
test_data_matrix[line[1]-1, line[1]-1]

0.0

In [33]:
from sklearn.metrics import pairwise_distances

In [35]:
user_similarity = pairwise_distances(train_data_matrix, metric = 'cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis]
rating_diff = (train_data_matrix-mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(rating_diff) /np.array([np.abs(user_similarity).sum(axis=1)]).T
pd.DataFrame(user_pred)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,1.518152,0.569133,0.472321,0.769993,0.489809,0.336967,1.336012,0.883677,1.127660,0.533089,...,0.275006,0.271737,0.274925,0.273863,0.274503,0.272977,0.271737,0.274218,0.274252,0.274048
1,1.280172,0.295397,0.155443,0.538457,0.188568,0.004179,1.112777,0.645927,0.845839,0.215789,...,-0.067599,-0.070884,-0.067962,-0.068936,-0.067737,-0.070031,-0.070884,-0.069177,-0.067613,-0.067447
2,1.298044,0.262105,0.130264,0.507501,0.156467,-0.023499,1.095841,0.618676,0.848605,0.194649,...,-0.097599,-0.100862,-0.098208,-0.099093,-0.097682,-0.100205,-0.100862,-0.099548,-0.097513,-0.097474
3,1.258997,0.239268,0.110098,0.482151,0.134495,-0.039530,1.060969,0.591205,0.822388,0.181339,...,-0.114304,-0.117449,-0.114202,-0.115284,-0.114320,-0.116576,-0.117449,-0.115703,-0.114118,-0.114109
4,1.326801,0.366518,0.273609,0.592863,0.290626,0.141218,1.158887,0.699594,0.967107,0.341233,...,0.069179,0.066035,0.069408,0.068284,0.069125,0.067255,0.066035,0.068476,0.068620,0.068790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.243890,0.284612,0.153711,0.524320,0.183802,0.013761,1.074469,0.629204,0.833138,0.224307,...,-0.059430,-0.062781,-0.059802,-0.060795,-0.059895,-0.061630,-0.062781,-0.060480,-0.059717,-0.059479
939,1.340572,0.339709,0.229928,0.550902,0.248424,0.083283,1.149520,0.649071,0.898228,0.290651,...,0.013409,0.010316,0.013511,0.012446,0.013128,0.011359,0.010316,0.012402,0.013057,0.013297
940,1.167207,0.234122,0.099133,0.476577,0.133954,-0.040466,0.988393,0.580498,0.784297,0.175070,...,-0.113030,-0.116594,-0.113264,-0.114374,-0.113678,-0.115499,-0.116594,-0.114405,-0.113564,-0.113289
941,1.326054,0.327543,0.223911,0.553557,0.241073,0.073380,1.152435,0.648620,0.908225,0.280848,...,0.001565,-0.001482,0.001405,0.000443,0.001502,-0.000402,-0.001482,0.000678,0.001367,0.001772
942,1.368100,0.380721,0.299066,0.602173,0.314807,0.174333,1.183549,0.724567,0.982765,0.379000,...,0.102750,0.099737,0.102724,0.101728,0.102786,0.100985,0.099737,0.102233,0.102014,0.102356