In [1]:
import os
os.chdir(r'D:\D\Edureka\Edureka - 24 June - Python\Class 17')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [6]:
x=dataset.iloc[:,3:13].values

In [8]:
y = dataset.iloc[:,13].values

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
labelencoder_x = LabelEncoder()
x[:,1] = labelencoder_x.fit_transform(x[:,1])

In [14]:
labelencoder_x = LabelEncoder()
x[:,2] = labelencoder_x.fit_transform(x[:,2])

In [15]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

In [17]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11
0,1.0,0.0,0.0,619.0,0.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88
1,0.0,0.0,1.0,608.0,0.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58
2,1.0,0.0,0.0,502.0,0.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57
3,1.0,0.0,0.0,699.0,0.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63
4,0.0,0.0,1.0,850.0,0.0,43.0,2.0,125510.82,1.0,1.0,1.0,79084.10
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.0,0.0,0.0,771.0,1.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64
9996,1.0,0.0,0.0,516.0,1.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77
9997,1.0,0.0,0.0,709.0,0.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58
9998,0.0,1.0,0.0,772.0,1.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52
9999,1.0,0.0,0.0,792.0,0.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=801, p=2)

In [22]:
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=801, p=2,
                     weights='uniform')

In [24]:
y_pred = classifier_knn.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1583,    0],
       [ 417,    0]], dtype=int64)

In [27]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='rbf')
classifier_svm.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [29]:
y_pred=classifier_svm.predict(x_test)

In [30]:
confusion_matrix(y_test, y_pred)

array([[1583,    0],
       [ 417,    0]], dtype=int64)

In [ ]:
!pip install xgboost

In [31]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [32]:
y_pred = classifier.predict(x_test)

In [33]:
confusion_matrix(y_test, y_pred)

array([[1536,   47],
       [ 219,  198]], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.867

In [36]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = x_train, y=y_train, cv=10)
accuracies.mean()

0.8627499999999999

In [37]:
accuracies.std()

0.0055845769759221685

In [38]:
accuracies

array([0.85375, 0.865  , 0.8625 , 0.86375, 0.86375, 0.8525 , 0.86   ,
       0.87   , 0.8675 , 0.86875])

In [39]:
os.chdir(r'C:\Users\Admin\Downloads')

In [41]:
dataset = pd.read_csv('Recommend.csv', names = ['user_id','movie_id','rating','timestamp'])

In [42]:
dataset

       user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [44]:
n_users = dataset.user_id.unique().shape[0]

In [46]:
n_movies=dataset.movie_id.unique().shape[0]

In [47]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(dataset, test_size=0.25)

In [48]:
train_data_matrix = np.zeros((n_users, n_movies))

In [50]:
pd.DataFrame(train_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

In [53]:
train_data_matrix[line[1]-1,line[2]-1]

4.0

In [59]:
train_data_matrix[243,707]

4.0

In [54]:
pd.DataFrame(train_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,5.0,0.0,0.0,3.0,3.0,5.0,0.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
list(train_data.itertuples())

[Pandas(Index=24892, user_id=435, movie_id=174, rating=5, timestamp=884131627),
 Pandas(Index=55764, user_id=244, movie_id=708, rating=4, timestamp=880607231),
 Pandas(Index=30724, user_id=95, movie_id=448, rating=3, timestamp=879197783),
 Pandas(Index=20283, user_id=90, movie_id=617, rating=4, timestamp=891383835),
 Pandas(Index=41604, user_id=495, movie_id=228, rating=5, timestamp=888632738),
 Pandas(Index=84410, user_id=886, movie_id=1067, rating=5, timestamp=876032509),
 Pandas(Index=62623, user_id=867, movie_id=258, rating=3, timestamp=880077751),
 Pandas(Index=30915, user_id=554, movie_id=696, rating=3, timestamp=876232023),
 Pandas(Index=4949, user_id=187, movie_id=70, rating=4, timestamp=879465394),
 Pandas(Index=94985, user_id=145, movie_id=293, rating=4, timestamp=875270276),
 Pandas(Index=59348, user_id=862, movie_id=210, rating=4, timestamp=879304410),
 Pandas(Index=87534, user_id=661, movie_id=496, rating=5, timestamp=876015530),
 Pandas(Index=88385, user_id=588, movie_id=821, rating=4, timestamp=890026339),
 Pandas(Index=14019, user_id=346, movie_id=291, rating=5, timestamp=875002643),
 Pandas(Index=8495, user_id=90, movie_id=166, rating=4, timestamp=891383423),
 Pandas(Index=99640, user_id=934, movie_id=419, rating=4, timestamp=891192849),
 Pandas(Index=47783, user_id=480, movie_id=661, rating=4, timestamp=891208327),
 Pandas(Index=69838, user_id=405, movie_id=65, rating=1, timestamp=885546379),
 Pandas(Index=67618, user_id=276, movie_id=217, rating=4, timestamp=874792692),
 Pandas(Index=90091, user_id=44, movie_id=190, rating=5, timestamp=878348000),
 Pandas(Index=79300, user_id=846, movie_id=178, rating=4, timestamp=883947630),
 Pandas(Index=79399, user_id=830, movie_id=176, rating=3, timestamp=891561673),
 Pandas(Index=1651, user_id=141, movie_id=826, rating=2, timestamp=884585437),
 Pandas(Index=80281, user_id=325, movie_id=408, rating=5, timestamp=891478307),
 Pandas(Index=20337, user_id=437, movie_id=50, rating=5, timestamp=881000958),
 Pandas(Index=7627, user_id=85, movie_id=499, rating=4, timestamp=879455114),
 Pandas(Index=73582, user_id=90, movie_id=209, rating=5, timestamp=891383173),
 Pandas(Index=50119, user_id=477, movie_id=369, rating=4, timestamp=875940836),
 Pandas(Index=43720, user_id=586, movie_id=240, rating=3, timestamp=884066799),
 Pandas(Index=36233, user_id=125, movie_id=1115, rating=3, timestamp=879454345),
 Pandas(Index=30113, user_id=301, movie_id=426, rating=4, timestamp=882076967),
 Pandas(Index=7427, user_id=311, movie_id=212, rating=3, timestamp=884366397),
 Pandas(Index=75069, user_id=868, movie_id=189, rating=5, timestamp=877109300),
 Pandas(Index=99872, user_id=535, movie_id=1170, rating=3, timestamp=879618019),
 Pandas(Index=38130, user_id=595, movie_id=763, rating=3, timestamp=886921551),
 Pandas(Index=31429, user_id=454, movie_id=474, rating=4, timestamp=881959917),
 Pandas(Index=53612, user_id=13, movie_id=398, rating=2, timestamp=882398410),
 Pandas(Index=82020, user_id=653, movie_id=96, rating=4, timestamp=878854145),
 Pandas(Index=48259, user_id=749, movie_id=49, rating=4, timestamp=878848137),
 Pandas(Index=29951, user_id=342, movie_id=68, rating=3, timestamp=875319992),
 Pandas(Index=75153, user_id=406, movie_id=466, rating=4, timestamp=879446228),
 Pandas(Index=96635, user_id=512, movie_id=186, rating=5, timestamp=888579520),
 Pandas(Index=59482, user_id=104, movie_id=127, rating=3, timestamp=888465201),
 Pandas(Index=94752, user_id=405, movie_id=1382, rating=1, timestamp=885549790),
 Pandas(Index=2268, user_id=311, movie_id=385, rating=5, timestamp=884365284),
 Pandas(Index=86131, user_id=921, movie_id=97, rating=2, timestamp=884673891),
 Pandas(Index=35726, user_id=619, movie_id=39, rating=2, timestamp=885954083),
 Pandas(Index=90207, user_id=374, movie_id=823, rating=1, timestamp=880936476),
 Pandas(Index=76876, user_id=642, movie_id=140, rating=3, timestamp=886569257),
 Pandas(Index=37150, user_id=249, movie_id=294, rating=3, timestamp=879571557),
 Pandas(Index=53655, user_id=796, movie_id=1119, rating=4, timestamp=892675528),
 Pandas(Index=75839, user_id=932, movie_id=611, rating=5, timestamp=891250418),
 Pandas(Index=86006, user_id=173, movie_id=258, rating=4, timestamp=877556625),
 Pandas(Index=10984, user_id=203, movie_id=1, rating=3, timestamp=880434384),
 Pandas(Index=78438, user_id=835, movie_id=288, rating=2, timestamp=891032224),
 Pandas(Index=52726, user_id=196, movie_id=153, rating=5, timestamp=881251820),
 Pandas(Index=69331, user_id=110, movie_id=939, rating=4, timestamp=886988042),
 Pandas(Index=36968, user_id=328, movie_id=729, rating=4, timestamp=885047737),
 Pandas(Index=4268, user_id=292, movie_id=525, rating=5, timestamp=881105701),
 Pandas(Index=85773, user_id=38, movie_id=433, rating=5, timestamp=892433771),
 Pandas(Index=23536, user_id=102, movie_id=319, rating=4, timestamp=875886434),
 Pandas(Index=21054, user_id=23, movie_id=408, rating=5, timestamp=874784538),
 Pandas(Index=46465, user_id=567, movie_id=582, rating=3, timestamp=882426899),
 Pandas(Index=92421, user_id=908, movie_id=558, rating=4, timestamp=879722667),
 Pandas(Index=19393, user_id=201, movie_id=100, rating=4, timestamp=884111485),
 Pandas(Index=90053, user_id=880, movie_id=1014, rating=4, timestamp=892959041),
 Pandas(Index=82168, user_id=303, movie_id=655, rating=5, timestamp=879483568),
 Pandas(Index=47109, user_id=379, movie_id=63, rating=2, timestamp=880962215),
 Pandas(Index=51649, user_id=672, movie_id=1061, rating=4, timestamp=879789566),
 Pandas(Index=84884, user_id=283, movie_id=732, rating=4, timestamp=879298239),
 Pandas(Index=55633, user_id=805, movie_id=470, rating=5, timestamp=881695872),
 Pandas(Index=63938, user_id=774, movie_id=227, rating=5, timestamp=888557383),
 Pandas(Index=94790, user_id=429, movie_id=156, rating=4, timestamp=882384920),
 Pandas(Index=10967, user_id=385, movie_id=340, rating=4, timestamp=879438647),
 Pandas(Index=9292, user_id=18, movie_id=57, rating=4, timestamp=880130930),
 Pandas(Index=99985, user_id=617, movie_id=582, rating=4, timestamp=883789294),
 Pandas(Index=66795, user_id=604, movie_id=441, rating=2, timestamp=883668261),
 Pandas(Index=86133, user_id=834, movie_id=276, rating=5, timestamp=890862468),
 Pandas(Index=48478, user_id=524, movie_id=204, rating=3, timestamp=884635358),
 Pandas(Index=15539, user_id=10, movie_id=195, rating=4, timestamp=877889130),
 Pandas(Index=61075, user_id=577, movie_id=82, rating=4, timestamp=880474433),
 Pandas(Index=18089, user_id=329, movie_id=288, rating=2, timestamp=891655191),
 Pandas(Index=54900, user_id=709, movie_id=637, rating=3, timestamp=879848168),
 Pandas(Index=57673, user_id=758, movie_id=578, rating=4, timestamp=881977872),
 Pandas(Index=25255, user_id=1, movie_id=32, rating=5, timestamp=888732909),
 Pandas(Index=13153, user_id=276, movie_id=1471, rating=2, timestamp=877934947),
 Pandas(Index=11859, user_id=1, movie_id=232, rating=3, timestamp=878543196),
 Pandas(Index=32868, user_id=13, movie_id=484, rating=5, timestamp=882139804),
 Pandas(Index=95821, user_id=842, movie_id=303, rating=5, timestamp=891218002),
 Pandas(Index=98534, user_id=798, movie_id=930, rating=5, timestamp=875637661),
 Pandas(Index=48520, user_id=113, movie_id=1251, rating=5, timestamp=875325377),
 Pandas(Index=23022, user_id=123, movie_id=197, rating=5, timestamp=879872066),
 Pandas(Index=49258, user_id=586, movie_id=1273, rating=4, timestamp=884065825),
 Pandas(Index=65820, user_id=620, movie_id=63, rating=5, timestamp=889988232),
 Pandas(Index=58996, user_id=419, movie_id=50, rating=5, timestamp=879435541),
 Pandas(Index=23672, user_id=344, movie_id=385, rating=2, timestamp=884901503),
 Pandas(Index=56515, user_id=743, movie_id=298, rating=4, timestamp=881278061),
 Pandas(Index=77319, user_id=758, movie_id=124, rating=5, timestamp=884999132),
 Pandas(Index=77491, user_id=824, movie_id=288, rating=3, timestamp=877020927),
 Pandas(Index=2404, user_id=56, movie_id=797, rating=4, timestamp=892910860),
 Pandas(Index=76785, user_id=388, movie_id=328, rating=4, timestamp=886439561),
 Pandas(Index=44312, user_id=180, movie_id=961, rating=5, timestamp=877544384),
 Pandas(Index=9895, user_id=387, movie_id=692, rating=1, timestamp=886482928),
 Pandas(Index=29943, user_id=482, movie_id=301, rating=4, timestamp=887643315),
 Pandas(Index=41958, user_id=531, movie_id=288, rating=1, timestamp=887048686),
 Pandas(Index=78629, user_id=815, movie_id=176, rating=4, timestamp=878694705),
 Pandas(Index=83605, user_id=887, movie_id=476, rating=1, timestamp=881379059),
 Pandas(Index=29613, user_id=347, movie_id=276, rating=3, timestamp=881652657),
 Pandas(Index=46117, user_id=321, movie_id=1050, rating=3, timestamp=879441336),
 Pandas(Index=63145, user_id=848, movie_id=99, rating=3, timestamp=887038397),
 Pandas(Index=80340, user_id=234, movie_id=631, rating=3, timestamp=892334577),
 Pandas(Index=21977, user_id=405, movie_id=400, rating=1, timestamp=885549044),
 Pandas(Index=26497, user_id=115, movie_id=33, rating=4, timestamp=881171693),
 Pandas(Index=7588, user_id=207, movie_id=28, rating=4, timestamp=877822162),
 Pandas(Index=53948, user_id=748, movie_id=196, rating=3, timestamp=879454958),
 Pandas(Index=71378, user_id=178, movie_id=410, rating=4, timestamp=882824467),
 Pandas(Index=84813, user_id=932, movie_id=1126, rating=5, timestamp=891250862),
 Pandas(Index=2203, user_id=83, movie_id=118, rating=3, timestamp=880307071),
 Pandas(Index=31113, user_id=539, movie_id=242, rating=5, timestamp=879787770),
 Pandas(Index=13563, user_id=141, movie_id=295, rating=5, timestamp=884585039),
 Pandas(Index=13068, user_id=373, movie_id=20, rating=2, timestamp=877098751),
 Pandas(Index=23487, user_id=445, movie_id=845, rating=2, timestamp=891200320),
 Pandas(Index=10722, user_id=303, movie_id=232, rating=4, timestamp=879467191),
 Pandas(Index=79888, user_id=781, movie_id=286, rating=1, timestamp=879633495),
 Pandas(Index=73619, user_id=833, movie_id=1118, rating=3, timestamp=875133924),
 Pandas(Index=60054, user_id=493, movie_id=182, rating=5, timestamp=884130971),
 Pandas(Index=9620, user_id=151, movie_id=736, rating=4, timestamp=879542389),
 Pandas(Index=79986, user_id=585, movie_id=509, rating=4, timestamp=891283000),
 Pandas(Index=99758, user_id=807, movie_id=204, rating=4, timestamp=892528954),
 Pandas(Index=2892, user_id=85, movie_id=629, rating=3, timestamp=879454685),
 Pandas(Index=50897, user_id=613, movie_id=1, rating=4, timestamp=891227410),
 Pandas(Index=53811, user_id=7, movie_id=638, rating=4, timestamp=892132122),
 Pandas(Index=36072, user_id=430, movie_id=56, rating=4, timestamp=877226323),
 Pandas(Index=13859, user_id=206, movie_id=314, rating=1, timestamp=888179948),
 Pandas(Index=83617, user_id=267, movie_id=188, rating=5, timestamp=878971745),
 Pandas(Index=33496, user_id=336, movie_id=186, rating=4, timestamp=877757730),
 Pandas(Index=36338, user_id=195, movie_id=740, rating=3, timestamp=890985743),
 Pandas(Index=97911, user_id=731, movie_id=496, rating=5, timestamp=886179040),
 Pandas(Index=22948, user_id=437, movie_id=433, rating=3, timestamp=880140369),
 Pandas(Index=24573, user_id=48, movie_id=1064, rating=4, timestamp=879434688),
 Pandas(Index=31933, user_id=299, movie_id=255, rating=2, timestamp=877878036),
 Pandas(Index=7286, user_id=280, movie_id=790, rating=4, timestamp=891702013),
 Pandas(Index=84641, user_id=717, movie_id=121, rating=2, timestamp=884642762),
 Pandas(Index=43442, user_id=416, movie_id=333, rating=4, timestamp=876696788),
 Pandas(Index=73056, user_id=483, movie_id=50, rating=5, timestamp=878953485),
 Pandas(Index=64669, user_id=825, movie_id=14, rating=3, timestamp=880755942),
 Pandas(Index=80139, user_id=839, movie_id=258, rating=4, timestamp=875751411),
 Pandas(Index=81428, user_id=345, movie_id=244, rating=3, timestamp=884994658),
 Pandas(Index=56364, user_id=698, movie_id=1299, rating=2, timestamp=886367775),
 Pandas(Index=53246, user_id=334, movie_id=172, rating=3, timestamp=891548954),
 Pandas(Index=66727, user_id=363, movie_id=549, rating=4, timestamp=891496225),
 Pandas(Index=4632, user_id=287, movie_id=218, rating=5, timestamp=875335424),
 Pandas(Index=93672, user_id=711, movie_id=472, rating=1, timestamp=879991585),
 Pandas(Index=80959, user_id=650, movie_id=315, rating=3, timestamp=891368885),
 Pandas(Index=81997, user_id=882, movie_id=405, rating=4, timestamp=879861939),
 Pandas(Index=68127, user_id=618, movie_id=420, rating=3, timestamp=891309163),
 Pandas(Index=45295, user_id=236, movie_id=100, rating=3, timestamp=890116402),
 Pandas(Index=22081, user_id=171, movie_id=340, rating=3, timestamp=891034756),
 Pandas(Index=10173, user_id=276, movie_id=141, rating=4, timestamp=874792870),
 Pandas(Index=5633, user_id=6, movie_id=498, rating=4, timestamp=883601053),
 Pandas(Index=40198, user_id=164, movie_id=252, rating=4, timestamp=889402265),
 Pandas(Index=7461, user_id=94, movie_id=380, rating=3, timestamp=891722760),
 Pandas(Index=11527, user_id=87, movie_id=25, rating=4, timestamp=879876811),
 Pandas(Index=79796, user_id=868, movie_id=217, rating=2, timestamp=877109895),
 Pandas(Index=79060, user_id=551, movie_id=1439, rating=5, timestamp=892783612),
 Pandas(Index=42996, user_id=650, movie_id=637, rating=3, timestamp=891387353),
 Pandas(Index=86283, user_id=901, movie_id=932, rating=4, timestamp=877127021),
 Pandas(Index=35051, user_id=457, movie_id=186, rating=5, timestamp=882397575),
 Pandas(Index=47068, user_id=81, movie_id=269, rating=3, timestamp=876533229),
 Pandas(Index=34453, user_id=336, movie_id=88, rating=2, timestamp=877757910),
 Pandas(Index=53551, user_id=339, movie_id=238, rating=5, timestamp=891032827),
 Pandas(Index=47276, user_id=279, movie_id=926, rating=4, timestamp=875296696),
 Pandas(Index=90576, user_id=938, movie_id=456, rating=1, timestamp=891357161),
 Pandas(Index=96035, user_id=551, movie_id=245, rating=3, timestamp=892775723),
 Pandas(Index=16484, user_id=181, movie_id=1165, rating=1, timestamp=878962496),
 Pandas(Index=32471, user_id=494, movie_id=322, rating=2, timestamp=879540819),
 Pandas(Index=92630, user_id=106, movie_id=318, rating=5, timestamp=881449830),
 Pandas(Index=4817, user_id=291, movie_id=558, rating=4, timestamp=874867757),
 Pandas(Index=63957, user_id=881, movie_id=642, rating=4, timestamp=876538027),
 Pandas(Index=65730, user_id=378, movie_id=543, rating=4, timestamp=880055840),
 Pandas(Index=53093, user_id=758, movie_id=286, rating=5, timestamp=880672230),
 Pandas(Index=39446, user_id=617, movie_id=89, rating=4, timestamp=883789294),
 Pandas(Index=26545, user_id=492, movie_id=127, rating=5, timestamp=879969879),
 Pandas(Index=57410, user_id=823, movie_id=144, rating=5, timestamp=878438535),
 Pandas(Index=15098, user_id=344, movie_id=660, rating=3, timestamp=884901235),
 Pandas(Index=32307, user_id=506, movie_id=28, rating=4, timestamp=874874308),
 Pandas(Index=66854, user_id=500, movie_id=183, rating=4, timestamp=883873461),
 Pandas(Index=89168, user_id=385, movie_id=204, rating=1, timestamp=879441728),
 Pandas(Index=44555, user_id=621, movie_id=268, rating=4, timestamp=890517367),
 Pandas(Index=96230, user_id=896, movie_id=19, rating=2, timestamp=887159211),
 Pandas(Index=60657, user_id=879, movie_id=300, rating=3, timestamp=887760802),
 Pandas(Index=15842, user_id=289, movie_id=147, rating=3, timestamp=876789581),
 Pandas(Index=20138, user_id=48, movie_id=647, rating=4, timestamp=879434819),
 Pandas(Index=18035, user_id=425, movie_id=475, rating=5, timestamp=878737945),
 Pandas(Index=48355, user_id=660, movie_id=216, rating=2, timestamp=891199804),
 Pandas(Index=70482, user_id=707, movie_id=747, rating=3, timestamp=886287900),
 Pandas(Index=53490, user_id=474, movie_id=566, rating=5, timestamp=887926632),
 Pandas(Index=8575, user_id=301, movie_id=160, rating=2, timestamp=882077284),
 Pandas(Index=4941, user_id=85, movie_id=709, rating=5, timestamp=879828941),
 Pandas(Index=64617, user_id=806, movie_id=433, rating=4, timestamp=882389523),
 Pandas(Index=98257, user_id=233, movie_id=845, rating=4, timestamp=880190627),
 Pandas(Index=60398, user_id=823, movie_id=732, rating=5, timestamp=878439183),
 Pandas(Index=18128, user_id=271, movie_id=882, rating=3, timestamp=885844547),
 Pandas(Index=84776, user_id=851, movie_id=127, rating=5, timestamp=891961664),
 Pandas(Index=29374, user_id=110, movie_id=41, rating=4, timestamp=886989399),
 Pandas(Index=73616, user_id=921, movie_id=1034, rating=3, timestamp=879380457),
 Pandas(Index=18932, user_id=95, movie_id=443, rating=3, timestamp=879198747),
 Pandas(Index=57903, user_id=253, movie_id=427, rating=5, timestamp=891628229),
 Pandas(Index=34454, user_id=233, movie_id=194, rating=4, timestamp=877663913),
 Pandas(Index=81891, user_id=622, movie_id=95, rating=4, timestamp=882669556),
 Pandas(Index=28548, user_id=256, movie_id=117, rating=5, timestamp=882150313),
 Pandas(Index=95416, user_id=648, movie_id=603, rating=5, timestamp=882212651),
 Pandas(Index=13031, user_id=334, movie_id=340, rating=3, timestamp=891544264),
 Pandas(Index=78624, user_id=642, movie_id=496, rating=4, timestamp=885603516),
 Pandas(Index=72473, user_id=600, movie_id=373, rating=3, timestamp=888452490),
 Pandas(Index=11277, user_id=254, movie_id=199, rating=4, timestamp=886472089),
 Pandas(Index=60608, user_id=805, movie_id=856, rating=4, timestamp=881698881),
 Pandas(Index=41036, user_id=77, movie_id=31, rating=3, timestamp=884753292),
 Pandas(Index=30994, user_id=491, movie_id=273, rating=5, timestamp=891188230),
 Pandas(Index=4285, user_id=94, movie_id=185, rating=5, timestamp=885873684),
 Pandas(Index=10866, user_id=262, movie_id=762, rating=2, timestamp=879790974),
 Pandas(Index=90469, user_id=222, movie_id=223, rating=4, timestamp=878181535),
 Pandas(Index=14986, user_id=405, movie_id=1176, rating=3, timestamp=885549942),
 Pandas(Index=99717, user_id=388, movie_id=53, rating=5, timestamp=886441248),
 Pandas(Index=40672, user_id=643, movie_id=928, rating=4, timestamp=891445660),
 Pandas(Index=99337, user_id=542, movie_id=132, rating=3, timestamp=886532620),
 Pandas(Index=59452, user_id=707, movie_id=224, rating=4, timestamp=880059876),
 Pandas(Index=82745, user_id=405, movie_id=1266, rating=1, timestamp=885549634),
 Pandas(Index=11212, user_id=7, movie_id=181, rating=3, timestamp=891351287),
 Pandas(Index=35026, user_id=586, movie_id=174, rating=4, timestamp=884058898),
 Pandas(Index=43345, user_id=188, movie_id=162, rating=4, timestamp=875072972),
 Pandas(Index=5011, user_id=16, movie_id=288, rating=3, timestamp=877717078),
 Pandas(Index=71755, user_id=468, movie_id=963, rating=5, timestamp=875286036),
 Pandas(Index=98633, user_id=852, movie_id=250, rating=4, timestamp=891036414),
 Pandas(Index=77954, user_id=164, movie_id=826, rating=4, timestamp=889402340),
 Pandas(Index=30308, user_id=271, movie_id=269, rating=4, timestamp=885844430),
 Pandas(Index=54512, user_id=189, movie_id=517, rating=4, timestamp=893265535),
 Pandas(Index=34212, user_id=309, movie_id=1296, rating=2, timestamp=877370319),
 Pandas(Index=16014, user_id=44, movie_id=193, rating=3, timestamp=878348521),
 Pandas(Index=28742, user_id=194, movie_id=182, rating=3, timestamp=879521475),
 Pandas(Index=81916, user_id=452, movie_id=94, rating=1, timestamp=888568349),
 Pandas(Index=26196, user_id=5, movie_id=392, rating=2, timestamp=875637330),
 Pandas(Index=57774, user_id=419, movie_id=79, rating=4, timestamp=879435590),
 Pandas(Index=30638, user_id=75, movie_id=111, rating=4, timestamp=884050502),
 Pandas(Index=59962, user_id=23, movie_id=171, rating=5, timestamp=874785809),
 Pandas(Index=5312, user_id=214, movie_id=208, rating=5, timestamp=892668153),
 Pandas(Index=76219, user_id=782, movie_id=127, rating=4, timestamp=891499213),
 Pandas(Index=14536, user_id=399, movie_id=986, rating=3, timestamp=882341586),
 Pandas(Index=84856, user_id=87, movie_id=372, rating=3, timestamp=879876565),
 Pandas(Index=97163, user_id=308, movie_id=429, rating=4, timestamp=887737890),
 Pandas(Index=71135, user_id=561, movie_id=210, rating=3, timestamp=885809146),

In [ ]:
for line in test_data.itertuples():
    tes[line[1]-1, line[2]-1] = line[3]

In [60]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]

In [61]:
pd.DataFrame(test_data_matrix)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,3.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
from sklearn.metrics import pairwise_distances

In [64]:
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]

In [65]:
rating_diff = (train_data_matrix-mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(rating_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T

In [67]:
df_out = pd.DataFrame(user_pred)

In [68]:
df_out.to_csv('output.csv')